import enum

VBAN_HEADER_SIZE        = (4 + 4 + 16 + 4)
VBAN_HEADER_FOURC       = 'NABV'
VBAN_STREAM_NAME_SIZE   = 16
VBAN_PROTOCOL_MAX_SIZE  = 1464
VBAN_DATA_MAX_SIZE      = (VBAN_PROTOCOL_MAX_SIZE - VBAN_HEADER_SIZE)
VBAN_CHANNELS_MAX_NB    = 256
VBAN_SAMPLES_MAX_NB     = 256

VBAN_PROTOCOL_MASK = 0xE0
class VBANProtocols(enum.Enum):
    VBAN_PROTOCOL_AUDIO         = 0x00
    VBAN_PROTOCOL_SERIAL        = 0x20
    VBAN_PROTOCOL_TXT           = 0x40
    VBAN_PROTOCOL_SERVICE       = 0x60
    VBAN_PROTOCOL_UNDEFINED_1   = 0x80
    VBAN_PROTOCOL_UNDEFINED_2   = 0xA0
    VBAN_PROTOCOL_UNDEFINED_3   = 0xC0
    VBAN_PROTOCOL_UNDEFINED_4   = 0xE0
