import enum

VBAN_TEXT_STREAM_TYPE_MASK = 0xF0
class VBANTextStreamType(enum.Enum):
    VBAN_TEXT_STREAM_TYPE_ASCII       = 0x00
    VBAN_TEXT_STREAM_TYPE_UTF_8       = 0x10
    VBAN_TEXT_STREAM_TYPE_WCHAR       = 0x20
    VBAN_TEXT_STREAM_TYPE_UNDEFINED1  = 0x30
    VBAN_TEXT_STREAM_TYPE_UNDEFINED2  = 0x40
    VBAN_TEXT_STREAM_TYPE_UNDEFINED3  = 0x50
    VBAN_TEXT_STREAM_TYPE_UNDEFINED4  = 0x60
    VBAN_TEXT_STREAM_TYPE_UNDEFINED5  = 0x70
    VBAN_TEXT_STREAM_TYPE_UNDEFINED6  = 0x80
    VBAN_TEXT_STREAM_TYPE_UNDEFINED7  = 0x90
    VBAN_TEXT_STREAM_TYPE_UNDEFINED8  = 0xA0
    VBAN_TEXT_STREAM_TYPE_UNDEFINED9  = 0xB0
    VBAN_TEXT_STREAM_TYPE_UNDEFINED10 = 0xC0
    VBAN_TEXT_STREAM_TYPE_UNDEFINED11 = 0xD0
    VBAN_TEXT_STREAM_TYPE_UNDEFINED12 = 0xE0
    VBAN_TEXT_STREAM_TYPE_USER        = 0xF0

